export const lesson001: BM.Lesson = {
    id: 0,
    name: 'Nombor dan Hari (numbers and days)',
    cards: [
        { bm: 'hari minggu', eng: 'weekend' },
        { bm: 'hari bulan', eng: 'date' },
        { bm: '-ratus', eng: 'hundred' },
        { bm: '-ribus', eng: 'thousand' },
        { bm: 'pertamah', eng: 'first' },
        { bm: 'kedua, ketiga, ke-4...', eng: 'second, third, fourth...' },
        { bm: 'tempat', eng: 'place' },
        { bm: 'saya tempat pertamah', eng: 'I placed first' },
        { bm: 'tapat', eng: 'get' },
        { bm: 'suku', eng: 'quarter' },
        { bm: 'setengah', eng: 'half' },
        { bm: 'lapan suku', eng: '8:15' },
        { bm: 'Pukul berapah sekarah?', eng: 'What time is it?' },
        { bm: 'Pukul enam setengah', eng: 'Half past six' },
    ],
}
