export const lesson002: BM.Lesson = {
    id: 2,
    name: 'Keluarga Saya',
    cards: [
        { bm: 'perempuan', en: 'girl', tags: ['vocab'] },
        { bm: 'lelaki', en: 'boy', tags: ['vocab'] },
        { bm: 'laki', en: 'boy', tags: ['vocab'] },
        { bm: 'atuk', en: 'grandpa', tags: ['vocab'] },
        { bm: 'datuk', en: 'grandpa', tags: ['vocab'] },
        { bm: 'nenek', en: 'grandma', tags: ['vocab'] },
        { bm: 'ayah', en: 'dad', tags: ['vocab'] },
        { bm: 'bapa', en: 'father', tags: ['vocab'] },
        { bm: 'emak', en: 'mom', tags: ['vocab'] },
        { bm: 'ibu', en: 'mother', tags: ['vocab'] },
        { bm: 'mak', en: 'mom', tags: ['vocab'] },
        { bm: 'abang', en: 'brother', tags: ['vocab'] },
        { bm: 'bang', en: 'brother', tags: ['vocab'] },
        { bm: 'kakak', en: 'sister', tags: ['vocab'] },
        { bm: 'kak', en: 'sister', tags: ['vocab'] },
        { bm: 'adik lelaki', en: 'little brother', tags: ['vocab'] },
        { bm: 'adik perempuan', en: 'little sister', tags: ['vocab'] },
        { bm: 'bayi', en: 'baby', tags: ['vocab'] },
        { bm: '-cik', en: 'formal ms/mr', tags: ['vocab'] },
        {
            bm: 'makcik',
            en: 'aunt/general respectful address',
            tags: ['vocab'],
        },
        {
            bm: 'pakcik',
            en: 'uncle/general respectful address',
            tags: ['vocab'],
        },
        { bm: 'encik', en: 'mr', tags: ['vocab'] },
        { bm: 'puan', en: 'mrs', tags: ['vocab'] },
        {
            bm: 'tuan-tuan dan puan-puan',
            en: 'gentlemen & ladies',
            tags: ['vocab'],
        },
        { bm: 'tuan', en: 'master', tags: ['vocab'] },
        { bm: 'sangat', en: 'very', tags: ['vocab'] },
        { bm: 'main', en: 'play', tags: ['vocab'] },
        { bm: 'bola sepak', en: 'football', tags: ['vocab'] },
        { bm: 'sediap hari', en: 'every day', tags: ['vocab'] },
        { bm: 'Ini siapa?', en: 'Who is this?', tags: ['vocab'] },
    ],
}
