export const lesson002: BM.Lesson = {
    id: 2,
    name: 'Keluarga Saya (my family)',
    cards: [
        { bm: 'perempuan', eng: 'girl' },
        { bm: 'lelaki', eng: 'boy' },
        { bm: 'laki', eng: 'boy' },
        { bm: 'atuk', eng: 'grandpa' },
        { bm: 'datuk', eng: 'grandpa' },
        { bm: 'nenek', eng: 'grandma' },
        { bm: 'ayah', eng: 'dad' },
        { bm: 'bapa', eng: 'father' },
        { bm: 'emak', eng: 'mom' },
        { bm: 'ibu', eng: 'mother' },
        { bm: 'mak', eng: 'mom' },
        { bm: 'abang', eng: 'brother' },
        { bm: 'bang', eng: 'brother' },
        { bm: 'kakak', eng: 'sister' },
        { bm: 'kak', eng: 'sister' },
        { bm: 'adik lelaki', eng: 'little brother' },
        { bm: 'adik perempuan', eng: 'little sister' },
        { bm: 'bayi', eng: 'baby' },
        { bm: '-cik', eng: 'formal ms/mr' },
        { bm: 'makcik', eng: 'aunt/general respectful address' },
        { bm: 'pakcik', eng: 'uncle/general respectful address' },
        { bm: 'encik', eng: 'mr' },
        { bm: 'puan', eng: 'mrs' },
        { bm: 'tuan-tuan dan puan-puan', eng: 'gentlemen & ladies' },
        { bm: 'tuan', eng: 'master' },
        { bm: 'sangat', eng: 'very' },
        { bm: 'main', eng: 'play' },
        { bm: 'bola sepak', eng: 'football' },
        { bm: 'sediap hari', eng: 'every day' },
    ],
}
