export const lesson001: BM.Lesson = {
    id: 1,
    name: 'Nombor dan Hari',
    cards: [
        { bm: 'hujung minggu', en: 'weekend', tags: ['vocab'] },
        { bm: 'hari bulan', en: 'date', tags: ['vocab'] },
        { bm: '-ratus', en: 'hundred' },
        { bm: '-ribus', en: 'thousand' },
        { bm: 'pertamah', en: 'first', tags: ['vocab'] },
        { bm: 'kedua, ketiga, ke-4...', en: 'second, third, fourth...' },
        { bm: 'tempat', en: 'place', tags: ['vocab'] },
        { bm: 'saya tempat pertamah', en: 'I placed first' },
        { bm: 'tapat', en: 'get', tags: ['vocab'] },
        { bm: 'suku', en: 'quarter', tags: ['vocab'] },
        { bm: 'setengah', en: 'half', tags: ['vocab'] },
        { bm: 'lapan suku', en: '8:15', tags: ['vocab'] },
        {
            bm: 'Sekarang pukul berapa?',
            en: 'What time is it?',
            tags: ['q/a'],
        },
        { bm: 'Pukul enam setengah', en: 'Half past six', tags: ['q/a'] },
        { bm: 'Hari ni hari ____', en: 'Today is _____', tags: ['q/a'] },
        { bm: 'Esok hari apa?', en: 'What day is tomorrow?', tags: ['q/a'] },
        {
            bm: 'Semalam hari apa?',
            en: 'What day was yesterday?',
            tags: ['q/a'],
        },
    ],
}
